import ChallengeBox from "../components/ChallengeBox"


export const getServerSideProps = async () => {
    // Fetch data from external API
    const res = await fetch(`https://asvz.ch/asvz_api/sport_search?_format=json&limit=999`); //can use await bc. async
    const data = await res.json();

    const titleData = {} // "title": desc

    //console.log(Object.keys(data))


    data.results.forEach(element => {
        titleData[element.title] = {
            summary: element.summary,
            number: element.nid
        } 
    });


    // Pass data to the page via props
    return { props: { titleData } }

}


export default function Challenges(props) {

    var hrefSignUp = "https://www.asvz.ch/en/node/426?f[0]=sport:"
    var sportsList = ["Basketball", "Jujitsu", "Judo"]

    //when initializing user and competitor set initial value by passing a request to the server
    return (
        <>
            <ChallengeBox user={100} competitor={5} sportsData = {props.titleData} href = {hrefSignUp} sports = {sportsList}/>
        </>
        //eventually have another props attribute which passes the random assignments generated by the backend
    )
}

